/* WITH CTE AS (

),

CTE2 AS (
    stuff
    FROM CTE
),

CTE3 AS(
    stuff FROM CTE2
)

SELECT * FROM CTE3

*/


WITH CTE AS(
SELECT
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT, -- Column name
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

CASE WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
THEN 'WEEKEND'
ELSE 'BUSINESS DAY'
END AS DAY_TYPE,

CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2)
    THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,4,5)
    THEN 'SPRING'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8)
    THEN 'SUMMER'
    ELSE 'AUTUM'
    END AS STATION_OF_YEAR

FROM
{{source('demo','bike')}}
WHERE STARTED_AT !='started_at'

)

SELECT
*
FROM CTE

